
import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { format } from "date-fns";
import { FileText, User, Calendar, Activity, Bot, Target, AlertTriangle, List, CheckCircle, Loader2 } from "lucide-react";
import { Separator } from "@/components/ui/separator";

export default async function ReportViewPage({ params }: { params: { id: string } }) {
  const supabase = createClient();
  const { data: report, error } = await supabase
    .from("audit_reports")
    .select("*, generated_by_user:profiles(full_name)")
    .eq("id", params.id)
    .single();

  if (error || !report) {
    notFound();
  }

  const renderFormattedText = (text: string | null) => {
    if (!text) return <p className="text-muted-foreground">N/A</p>;
    return text.split('\n').map((paragraph, index) => (
      <p key={index} className="mb-2 last:mb-0">{paragraph}</p>
    ));
  };
  
  const getStatusIcon = (status: string) => {
    switch (status) {
        case 'final': return <CheckCircle className="h-5 w-5 text-green-600" />;
        case 'draft': return <Loader2 className="h-5 w-5 text-yellow-600 animate-spin" />;
        case 'failed': return <AlertTriangle className="h-5 w-5 text-red-600" />;
        default: return <Activity className="h-5 w-5 text-gray-500" />;
    }
  }


  return (
    <div className="space-y-8 max-w-4xl mx-auto">
        <div>
            <h1 className="text-3xl font-bold tracking-tight font-headline">{report.title}</h1>
            <p className="text-muted-foreground">
                An AI-generated audit report.
            </p>
        </div>
        
      <div className="grid gap-6 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Generated By</CardTitle>
            <User className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-lg font-bold">{report.generated_by_user?.full_name ?? 'System'}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Date Generated</CardTitle>
            <Calendar className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-lg font-bold">{format(new Date(report.created_at), 'PPP')}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Status</CardTitle>
             {getStatusIcon(report.status)}
          </CardHeader>
          <CardContent>
            <div className="text-lg font-bold capitalize">{report.status}</div>
          </CardContent>
        </Card>
      </div>

      {report.status === 'final' ? (
        <div className="space-y-6">
            <Card>
                <CardHeader>
                <CardTitle className="flex items-center gap-2"><Bot /> Executive Summary</CardTitle>
                <CardDescription>A high-level overview generated by the AI based on the provided records.</CardDescription>
                </CardHeader>
                <CardContent className="prose prose-sm dark:prose-invert max-w-none text-muted-foreground">
                    {renderFormattedText(report.summary)}
                </CardContent>
            </Card>
            
            <Card>
                <CardHeader>
                <CardTitle className="flex items-center gap-2"><Target /> Key Metrics</CardTitle>
                <CardDescription>Important financial metrics identified by the AI analysis.</CardDescription>
                </CardHeader>
                <CardContent className="prose prose-sm dark:prose-invert max-w-none text-muted-foreground">
                    {renderFormattedText(report.key_metrics)}
                </CardContent>
            </Card>

            <Card>
                <CardHeader>
                <CardTitle className="flex items-center gap-2"><AlertTriangle /> Top Risk Areas</CardTitle>
                <CardDescription>The most significant potential risks and anomalies found in the documents.</CardDescription>
                </CardHeader>
                <CardContent className="prose prose-sm dark:prose-invert max-w-none text-muted-foreground">
                     {renderFormattedText(report.top_risk_areas)}
                </CardContent>
            </Card>

            <Card>
                <CardHeader>
                <CardTitle className="flex items-center gap-2"><List /> Recommendations</CardTitle>
                <CardDescription>Actionable recommendations provided by the AI to mitigate risks and improve compliance.</CardDescription>
                </CardHeader>
                <CardContent className="prose prose-sm dark:prose-invert max-w-none text-muted-foreground">
                    {renderFormattedText(report.recommendations)}
                </CardContent>
            </Card>
        </div>
      ) : (
         <Card className="text-center py-12">
            <CardContent className="flex flex-col items-center gap-4">
                 {getStatusIcon(report.status)}
                <h2 className="text-xl font-semibold">Report is {report.status}...</h2>
                <p className="text-muted-foreground">Please check back in a moment. This page will not auto-refresh.</p>
            </CardContent>
         </Card>
      )}

    </div>
  );
}
