
import { createClient } from "@/lib/supabase/server";
import { ListChecks, PlusCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Badge } from "@/components/ui/badge";
import { format } from 'date-fns';

export default async function ReportsPage() {
    const supabase = createClient();
    const { data: reports, error } = await supabase
        .from('audit_reports')
        .select('*, generated_by_user:profiles(full_name)')
        .order('created_at', { ascending: false });

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <div>
            <h1 className="text-3xl font-bold tracking-tight font-headline">Audit Reports</h1>
            <p className="text-muted-foreground">
              Create, view, and manage your generated audit reports.
            </p>
        </div>
        <Button asChild>
            <Link href="/dashboard/reports/new">
                <PlusCircle className="mr-2 h-4 w-4" />
                New Report
            </Link>
        </Button>
      </div>

       <Card>
        <CardHeader>
          <CardTitle>Generated Reports</CardTitle>
          <CardDescription>
            A list of all the reports generated for your organization.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Title</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Created At</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
                {reports && reports.length > 0 ? (
                    reports.map((report) => (
                        <TableRow key={report.id}>
                            <TableCell className="font-medium">{report.title}</TableCell>
                            <TableCell>{report.generated_by_user?.full_name}</TableCell>
                            <TableCell><Badge variant={report.status === 'final' ? 'default' : 'secondary'}>{report.status}</Badge></TableCell>
                            <TableCell>{format(new Date(report.created_at), 'PPP')}</TableCell>
                            <TableCell>
                                <Button asChild variant="outline" size="sm">
                                    <Link href={`/dashboard/reports/${report.id}`}>View Report</Link>
                                </Button>
                            </TableCell>
                        </TableRow>
                    ))
                ) : (
                    <TableRow>
                        <TableCell colSpan={5} className="h-24 text-center">
                            No reports generated yet.
                        </TableCell>
                    </TableRow>
                )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
